- ci/pipeline.yaml
- manifest.yml
Add pipeline which deploys to PaaS.
Enable continuous deploylements.
> BAU: add pipeline and deploy to PaaS

- src/main/resources/templates/home.mustache
Updated header to avoid any confusion
> Add header to dummy service

- manifest.yml
We have added client ID validation to the OIDC provider, use a valid ID here.
> ikXzZaOa: Add valid client ID to config

- manifest.yml
- src/main/java/uk/gov/di/config/RelyingPartyConfig.java
- src/main/java/uk/gov/di/handlers/OidcHandler.java
- src/main/resources/templates/userinfo.mustache
Add a logout button to the userinfo page
We want to be able to logout from the service.
https://github.com/alphagov/di-auth-oidc-provider/pull/59
> XytEISqB: Add a logout button to the userinfo page

- src/main/resources/templates/home.mustache
- src/main/resources/templates/userinfo.mustache
Add ids and text to various elements.
To facilitate automated testing.
> LTG-101: Add ids to elements to facilitate automated testing

- manifest.yml
- Update CLIENT_ID and CLIENT_SECRET for build Stub RP
- So it is configured to send requests to the beta OIDC provider
> BAU - Update CLIENT_ID and CLIENT_SECRET for build Stub RP

- manifest.yml
Please include a summary of the change.
Please include reason for the change and any other relevant context.
Please include links to PRs in other repositories relevant to this PR.
Delete this section if not needed.
> BAU - Update Client ID

- src/main/java/uk/gov/di/config/RelyingPartyConfig.java
- src/main/java/uk/gov/di/handlers/HomeHandler.java
- src/main/resources/templates/home.mustache
Make service name configurable using an env var
So we can deploy multiple RPs with different names and config
> GOVSI-514: make service name configurable using an env var

- ci/pipeline.yaml
- manifest.yml
> BAU - Read env vars into manifest

- ci/pipeline.yaml
- manifest.yml
Reverts alphagov/di-auth-stub-relying-party#40
> Revert "BAU - Read env vars into manifest"

- src/main/java/uk/gov/di/utils/Oidc.java
Update logout url.
The URL was incorrect.
> Update logout url to correct link

- src/main/resources/templates/userinfo.mustache
Update userinfo template with phone number property.
The phone number was not showing on screen.
> Update template with correct name for model property

- manifest.yml
- Add a Integration Stub RP
- To connect to our integration environment
> GOVSI-359 - Add a Integration Stub RP

- src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
- src/main/java/uk/gov/di/utils/Oidc.java
- Validate the signature of the ID token
- Now that we are using KMS for signing
> GOVSI-623 - Validate the signature of the ID token

- src/main/resources/templates/userinfo.mustache
Add link to account management.
This is for a demo.
> Add header link to account management (demo)

- src/main/resources/templates/home.mustache
- Update label names
- Make it clearer what journey we want by changing the labels to 2fa and no 2fa
> BAU - Update label names

- src/main/java/uk/gov/di/OidcRp.java
- src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
- src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
- src/main/java/uk/gov/di/utils/Oidc.java
- src/main/resources/templates/home.mustache
- src/main/resources/templates/userinfo.mustache
Update stub to provide options of how to sign in.
To add support for identity and more granular control of the authorize request.
> Update stub to support different login types

- src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
- src/main/java/uk/gov/di/utils/Oidc.java
- src/main/resources/templates/home.mustache
- The claims request will never be null so we should check the size of the entries
- To fix the journey
> AUTH-1259 - Fix the Claims request

- build.gradle
> AUTH-1208: Use Artifactory to pull dependencies rather than Maven Central

- src/main/java/uk/gov/di/OidcRp.java
- src/main/java/uk/gov/di/handlers/BackChannelLogoutHandler.java
- src/main/java/uk/gov/di/utils/Oidc.java
We don't support complex sessions in the Stubs, so just log out the parsed payload
> AUT-241: Stub out backchannel logout URI

- manifest.yml
> AUT-309: Use most recent version of JDK

- src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
Please include a summary of the change.
Please include reason for the change and any other relevant context.
Please include links to PRs in other repositories relevant to this PR.
Delete this section if not needed.
> BAU - Log out access token contents

- src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
- src/main/resources/templates/userinfo.mustache
- Display whether a core identity claim has been received
- We want to know whether a claim with the name `https://vocab.account.gov.uk/v1/coreIdentityJWT` has been received by the Stub and display true or false depending on that.
> AUT-385 - Display whether a core identity claim has been received

- src/main/resources/templates/home.mustache
Change labels on P0 and no LoC radios
To avoid any confusion
> AUT-364: Re-word Level of Confidence radios

- src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
- src/main/resources/templates/home.mustache
- Correct the claim name used
- Add claims to the auth request as a ClaimSetRequest.Entry
- So claims are added on to the auth request
> BAU - Correctly add claims to auth request when present

- src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
- Fix claim request
Please include reason for the change and any other relevant context.
Please include links to PRs in other repositories relevant to this PR.
Delete this section if not needed.
> BAU - Fix claim request

- src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
- src/main/resources/templates/userinfo.mustache
- Display whether a passport or address claim has been received
- We want to know when we successfully receive an address or passport claim. This will show a true or false determining if they've been received.
> AUT-403 - Display whether a passport or address claim has been received

- build.gradle
- src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
- src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
- src/main/java/uk/gov/di/handlers/BackChannelLogoutHandler.java
- src/main/java/uk/gov/di/handlers/ErrorHandler.java
- src/main/java/uk/gov/di/handlers/HomeHandler.java
- src/main/java/uk/gov/di/handlers/SignOutHandler.java
- src/main/java/uk/gov/di/handlers/SignedOutHandler.java
- src/main/java/uk/gov/di/utils/Oidc.java
- Add log4j dependency to StubRP
- Add logging to useful points so we can track a users journey in the Stub
- To help us debug
> AUT-386 - Add logging to Stub RP app

- build.gradle
- Add log4j-api dependency
Please include reason for the change and any other relevant context.
Please include links to PRs in other repositories relevant to this PR.
Delete this section if not needed.
> AUT-386 - Add log4j-api dependency

- src/main/java/uk/gov/di/OidcRp.java
Does exactly what it says on the tin.
> BAU: Set `Server` header in code

- src/main/java/uk/gov/di/utils/Oidc.java
Confirming changes we're making to the API
> BAU: Log out token expiry if present

- src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
- src/main/resources/templates/home.mustache
Currently not checked by default unlike other claims
> BAU: Add support for driving permit claim

- src/main/resources/templates/home.mustache
The domain was wrong in the previous PR
> BAU: Correct claim name to use real domain

- src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
- src/main/resources/templates/userinfo.mustache
- Show whether driving permit claim has been returned
- So we can know if it has successfully been returned
> BAU - Show whether driving permit claim has been returned

- manifest.yml
Pass identity signing public key into the stub from configuration
> BAU: Set up identity signing public key from variables

- .gitignore
- deploy-sandpit.sh
- src/main/java/uk/gov/di/utils/Oidc.java
Reverts alphagov/di-auth-stub-relying-party#194
> Revert "BAU: buildLogoutUri refactoring "

- .gitignore
- deploy-sandpit.sh
- src/main/java/uk/gov/di/utils/Oidc.java
Stub rp hygiene
Remove 'System.out'.
Git ignore and deploy sandpit tweaks.
Remove unecessary logging, make sure the stub can deploy to sandpit.
> BAU: stub rp hygiene

- .github/workflows/pre-merge-checks.yml
- .github/workflows/sonar-analysis-on-merge.yml
- build.gradle
- src/main/java/uk/gov/di/utils/PrivateKeyReader.java
- Add Sonar plugin to build.gradle
- Add GitHub action definitions for PR and post-merge checks
- Separately, SonarCloud app has been added to org and repo
- Separately, SonarCloud token has been added to repo secrets
Note: I also decided that if we were to introduce Github actions, it would be worth enforcing formatting (Spotless was already configured locally). Due to enabling Spotless in the pipeline, and turning off the 'ratchet from' setting (which meant it would only check the diff against main) Spotless identified some historic formatting issues. I therefore accepted the reformatting and folded it into this PR.
- In order to improve code analysis across the DI estate
> AUT-1610: Add SonarCloud to repo

- src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
- src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
- src/main/resources/templates/home.mustache
- src/main/resources/templates/userinfo.mustache
Update to reflect changes in [ATO-37](https://govukverify.atlassian.net/browse/ATO-37?atlOrigin=eyJpIjoiMmRkNzZhOWIxMzg5NGI2Njg1NmZhYjYxODFmYWZjYTciLCJwIjoiaiJ9) (adding NINO/social security record claim).
To provide support for the new claim
https://github.com/alphagov/di-authentication-api/pull/3437
[ATO-37]: https://govukverify.atlassian.net/browse/ATO-37?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATO-83: Add social security record claim

- README.MD
- src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
- src/main/java/uk/gov/di/utils/Oidc.java
- src/main/resources/templates/home.mustache
Accept rp_sid to send in auth request
https://github.com/govuk-one-login/authentication-api/pull/3641
> ATO-200: Add ability to pass rp_sid in auth request

- .gitignore
- stack-orchestration/README.md
- stack-orchestration/configuration/build/auth-rp-stub-ecr/parameters.json
- stack-orchestration/configuration/build/build-rp-stub-pipeline/parameters.json
- stack-orchestration/configuration/build/tags.json
- stack-orchestration/configuration/int/int-rp-stub-pipeline/parameters.json
- stack-orchestration/configuration/int/tags.json
- stack-orchestration/configuration/prod/prod-rp-stub-pipeline/parameters.json
- stack-orchestration/configuration/prod/tags.json
- stack-orchestration/configuration/stage/stage-rp-stub-pipeline/parameters.json
- stack-orchestration/configuration/stage/tags.json
- stack-orchestration/provision_all.sh
Add dev platform provided stacks
In order to move to AWS and secure pipelines
> ATO-223: Set up dev platform config and provisioning script

- src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
- src/main/java/uk/gov/di/utils/Oidc.java
- src/main/resources/templates/home.mustache
- src/main/resources/templates/post-page.mustache
Add id token to stub
So we can check the reauthenticate flow
> ATO-208: Add id token

- Dockerfile
- README.MD
- build.gradle
- docker-compose.yml
- src/main/java/uk/gov/di/OidcRp.java
- src/main/java/uk/gov/di/config/RelyingPartyConfig.java
- template.yaml
Creates the resources for the stub and doc app stub on AWS 
To migrate the stub off of paas
> ATO-154: Create cloudformation template
