alphagov/di-auth-stub-relying-party

ci/pipeline.yaml

Fix the Gradle version being used in the pipeline
Pipeline is failing.

BAU: Fix the Gradle image tag being used in the Concourse pipeline

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
manifest.yml
startup.sh

- Upgrade gradle to the app can run on java16
- Upgrade the version of java in the manifest so the app can run on java16 on the PaaS
- Add startup.sh script to make it easier to run the app locally

BAU - Upgrade to java 16

---

src/main/java/uk/gov/di/config/RelyingPartyConfig.java

Use the correct environment variable to determine what the logout URL is.
This is failing in PaaS due to picking up the auth callback URL in error.
#14

XytEISqB: Use correct environment variable for logout URL.

---

build.gradle

Enable debug on app JVM on port 8083
Useful for debugging applications.

BAU: Enable debug on app JVM

---

src/main/java/uk/gov/di/OidcRp.java
src/main/java/uk/gov/di/handlers/OidcHandler.java
src/main/resources/templates/userinfo.mustache

Use a form post and a real button to do the logout rather than a simple link. 
This allows you to put any RP specific logout logic before redirecting to IDP.
#14

XytEISqB: A better logout button

---

example-clients/python/requirements.txt

- Remove cherrypy dependency from python app
- It is not used so can be removed

BAU - Remove cherrypy dependency from python app

---

example-clients/python/app/oidc-rp.py
example-clients/python/requirements.txt
example-clients/python/startup.sh

- Use the same client credentials registered by the dummy RP
- Split out the registration endpoint. This won't be used but is there more for reference.
- Call the wellknown endpoint before the auth request to prevent the need to hardcode the details on the OIDC provider.
- Remove the cherrypy from requirements.txt as this is not used
- So we can reuse the credentials of the dummy RP and make it a closer representation of what a real RP might look like

vT7VtuIb - Update python client sample implementation

---

Dockerfile

Add Dockerfile for di-auth-stub-relying-party.
Support running locally on docker and docker compose.
https://github.com/alphagov/di-auth-oidc-provider/pull/98

LTG-101: add Dockerfile

---

ci/pipeline.yaml
manifest.yml
src/main/java/uk/gov/di/config/RelyingPartyConfig.java

- Create 2 instances of the Stub app. One to run in sandbox and one to run in the build environment.
- The Sandbox instance will run against the OP which was built in alpha whereas the Build instance will run against the what is currently being built in beta
- Change the domain of the Stub apps to include the environment E.G - di-auth-stub-relying-party-sandbox.london.cloudapps.digital
- Store the base urls in parameter store and build the URL in the RelyingPartyConfig instance. 
- So it is clear what environment each Stub app is running in 
- Hide the BaseURLs until there is more protection on the Lambda endpoints
- So we can have multiple versions of the Stub App running

BAU - Refactor Stub apps and pipeline

---

ci/pipeline.yaml
manifest.yml

Deploy a second RP for testing SSO.
Additional client registered in the API.
We need two different services so we can test SSO and logout across two RPs.

GOVSI-514: deploy a second RP for testing SSO

---

ci/pipeline.yaml

Add missing resource in pipeline.
Resource for the new second application is missing
#31

GOVSI-514: add missing resource in pipeline

---

.github/dependabot.yml

Enable Dependabot for the repo.
Ensure library versions are up-to-date.

BAU: enable Dependabot for the repo

---

build.gradle

Enforce a strict version for Jetty.
Transitive version is not the latest.

BAU: enforce a strict version for Jetty

---

src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java

Remove id token validation
As there currently isn't a mechanism to get the public key to validate the id token.

Remove id token validation

---

src/main/java/uk/gov/di/utils/Oidc.java

Add missing token params.
This causes validation to fail on the token endpoint as they are required.

add extra params to token request

---

ci/pipeline.yaml

- This value is different for each stub, correct value has been added to SSM as `build-stub-base-url-s2` parameter.
Callback URL needs to be correct for S2.

BAU: Update `STUB_BASE_URL`  env var on stub s2

---

build.gradle
ci/pipeline.yaml
manifest.yml
src/main/java/uk/gov/di/OidcRp.java
src/main/java/uk/gov/di/config/RelyingPartyConfig.java

- Use the `java-cfenv` to detect if running in PaaS
- Use `java-cfenv` to get application URIs from `VCAP_APPLICATION` environment variable
- If running in PaaS use port `8080` otherwise whatever is specified.
This is a better solution than injecting environment variables from the pipeline and storing the values in SSM.

BAU: Allow stubs to detect their own URLs and ports

---

manifest.yml

- Add the OP_BASE_URL and CLIENT_PRIVATE_KEY vars to the manifest
- Parameterise these so they can be injected at deploy time
To facilitate deployment from consolidated pipeline

GOVSI-679: Add missing environment variables to manifest

---

manifest.yml

Remove extra environments from `manifest.yml` and only have a single, parameterised, entry for the application. 
This avoids duplication and makes it easier to deploy multiple environments.

GOVSI-679: Make manifest.yml resuable for any number of deployments

---

src/main/java/uk/gov/di/utils/Oidc.java

Set the Read and Connection timeout to 30 seconds
- Are lambdas are slow so this gives it a bit of time before timing out when requesting the JWKS.json

GOVSI-623 - Set the Read and Connection timeout to 30 seconds

---

src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
src/main/java/uk/gov/di/utils/Oidc.java
src/main/resources/templates/home.mustache

- Add a second login button that will trigger a `Cl` login journey
To aid manual testing of the uplift journeys
https://github.com/alphagov/di-authentication-api/pull/620

GOVSI-820: Add Cl login button

---

src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
src/main/java/uk/gov/di/utils/Oidc.java
src/main/resources/templates/home.mustache

- Switch medium VTR to Cl.CM
- To reflect the changes in the API
https://github.com/alphagov/di-authentication-api/pull/647

BAU - Switch medium VTR to Cl.CM

---

manifest.yml
src/main/java/uk/gov/di/config/RelyingPartyConfig.java
src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
src/main/resources/templates/userinfo.mustache

Make 'my account' link configurable in the stub clients.
Each environment has a different account management instance.
Link is currently hard-coded to integration
https://github.com/alphagov/di-infrastructure/pull/61

GOVSI-834: make 'my account' link configurable in the stub clients

---

src/main/resources/templates/home.mustache

Provide id for sign in button
Acceptance tests look for the id in order to click on the button
#68

BAU: provide id for sign in button

---

src/main/resources/templates/home.mustache

- Fix Identity values in Stub
- These have changed to use numbers which identify the level of assurance rather than letters

BAU - Fix Identity values in Stub

---

build.gradle
src/main/java/uk/gov/di/OidcRp.java
src/main/java/uk/gov/di/config/RelyingPartyConfig.java
src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
src/main/java/uk/gov/di/handlers/HomeHandler.java
src/main/java/uk/gov/di/handlers/SignOutHandler.java
src/main/resources/templates/home.mustache
tools/spotless-gradle.properties

Giving a bit of TLC to our stub
- BAU: Create spotless configuration ratcheting from main
- BAU: Reformat and fix HTML
- BAU: Refactor configuration into provider methods. Apply Spotless
- BAU: Inline static fields to use providers directly
- BAU: Use `getenv().getOrDefault()` instead of our own logic
The UI now looks like:

BAU: Refactoring and applying linter

---

.gitignore
build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
manifest.yml

Ability to read .env file when running locally.
Set java version in build.gradle
Default configuration is hardcoded.  Some of this configuration is secret so need to be able to read it from environment variables when running locally.

AUTH-1444: ability to read .env file when running locally

---

src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
src/main/resources/templates/home.mustache

Add option to select P0 - none.
Option is selected by default and does not pass any P value on calling /authorize.
Gives us a way to test the non-IPV/authentication only journey explicitly.

AUTH-1444: add option to select P0 - none

---

manifest.yml

This also switches to using `buildpacks` because `buildpack` is a deprecated field

AUT-309: Fix buildpack URL

---

manifest.yml
src/main/java/uk/gov/di/config/RelyingPartyConfig.java
src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
src/main/java/uk/gov/di/handlers/HomeHandler.java
src/main/java/uk/gov/di/utils/Oidc.java
src/main/resources/templates/app-home.mustache

- When the ClientType is `app` then load up the `app-home.mustache` where the only scopes are `openid` and `doc-checking-app` which are already selected. This will differentiate it from the other stubs.
- When the user clicks `Continue` then call the `AuthorizeHandler` which will submit an auth requests using the secure JWT request object. This will be signed with the same RSA key as the PrivateKeyJWT.
- Use the same callback path for now as the other stub.
- Add CLIENT_TYPE to the manifest, this value will be set in concourse.
- So we can test out the journey from a Doc Checking App Stub

AUT-295 - Support a Doc Checking App Stub

---

src/main/java/uk/gov/di/handlers/AuthorizeHandler.java

- Check if ClientType is app
- It didn't seem to pick up the form parameters, maybe because it was defaulted it to checked. Go about this another way by checking that the ClientType is `app` and then trigger a secure request

AUT-295 - Check if ClientType is app

---

src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
src/main/java/uk/gov/di/utils/Oidc.java

- Scopes need to be a string instead of a list
- Otherwise it will not be able to be parsed

BAU - Scopes need to be a string instead of a list

---

src/main/java/uk/gov/di/utils/Oidc.java

Use the value of state in request object instead of the State object itself
- Otherwise it cannot be parsed

BAU - Use the value of state in request object instead of the State object itself

---

src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
src/main/resources/templates/doc-app-userinfo.mustache

- Return different view when doc app info is returned
- When the RP is a doc app RP then display the doc app credential as a JWT in the UI.
- Do not show the email or phone when the RP is an app client
- So we can see the credential which is returned from userinfo

BAU - Return different view when doc app info is returned

---

src/main/java/uk/gov/di/utils/Oidc.java

Remove client_id parameter from token request.
This parameter is optional and no longer supported.
https://github.com/alphagov/di-authentication-api/pull/1867

AUT-363: Remove client_id parameter from token request

---

src/main/resources/templates/home.mustache

- Update P0 option to send `P0`
- Add new option for "None" which won't send an LoC
We have added P0 support to the API, we should update the stub to allow us to test this.

AUT-364: Support sending of P0 level of confidence

---

deploy-sandpit.sh

- Add a command line switch to `deploy-sandpit.sh` to override the default location of the API repo
Missing from #142, required as not all devs will always store their related repos in the same place.

AUT-434: Allow to set different path to the API repo

---

src/main/java/uk/gov/di/utils/Oidc.java

- Make nonce mandatory in request object
- We always expect the nonce mandatory in the request object

BAU - Make nonce mandatory in request object

---

src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java

- Parse the doc app credential as a list
- The Doc App Credential claim will now contain a list of JWTs instead of a single JWT. Update the Stub to reflect this.
- For the time being we will only receive one in the list, so for now just display the 1st JWT in the list and assume it is the only one.

AUT-549 - Parse the doc app credential as a list

---

src/main/resources/templates/doc-app-userinfo.mustache

Remove logout button from doc app user info page.
For the doc app journey the user is not actually logged in, so they cannot actually log out.

AUT-581: Remove logout button from doc app user info page

---

deploy.sh
src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
src/main/java/uk/gov/di/utils/Oidc.java
src/main/resources/templates/home.mustache

Add ui_locals parameter for authorization.
Includes radio buttons for choice of language.
RPs populate this field so although we only support en and cy as primary languages we need to be able to deal with extended tags too, the 'cy-AR' button is there for this purpose.  There is much more extensive testing of tag handling in the unit and integration tests in the corresponding backend change
The RP should be able to request which language is used in Sign In.
Only supported languages can actually be chosen, fallback is English.
https://github.com/alphagov/di-authentication-api/pull/2292

AUT_590: Add ui_locales parameter for authorization

---

src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
src/main/resources/templates/userinfo.mustache

Modifies `AuthCallBackHandler` and `userinfo.mustache` to show the content of the core identity claim.
We'd like to see the identity that SPOT issues.
I've actually no idea how we test this - would be good to discus with someone from Auth.

BAU show the core identity on return to the stub

---

.gitignore
src/main/java/uk/gov/di/OidcRp.java
src/main/java/uk/gov/di/config/RelyingPartyConfig.java
src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
src/main/java/uk/gov/di/utils/CoreIdentityValidator.java
src/main/resources/templates/userinfo.mustache

The stub reads the CoreIdentity JWT from `/userinfo` if present but does not validate the signature.
This PR creates an environment variable, for the signing key, which if present will be used to check the signature on the JWT and output its validity.

BAU: Validate CoreIdentity JWT

---

src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
src/main/java/uk/gov/di/utils/Oidc.java
src/main/resources/templates/app-home.mustache

What needs to be done
Update stub to send out ui_locales query parameter and make sure we pass it correctly
The doc app stub represents the HMRC service that calls auth to launch the doc app journey.  The doc app journey will be translated into Welsh, orchestration needs to pass on language preferences from the service.
https://github.com/alphagov/di-authentication-api/pull/2424

AUT-775: Update stub to send out ui_locales

---

src/main/java/uk/gov/di/config/RelyingPartyConfig.java
src/main/java/uk/gov/di/utils/Oidc.java

- BAU: Parametrise expected id token signing algorithm
- BAU: Use built-in method to read metadata from baseurl
- BAU: Make clientId field actually a `ClientID`
- BAU: Use issuer directly off metadata
- BAU: Sign authorization and token JWTs with same method
- BAU: Remove extraaneous semicolon

BAU: Refactorings (`Oidc`)

---

src/main/java/uk/gov/di/utils/Oidc.java

Handle trailing '/' on op_base_url for logout.
A trailing '/' was added to the op_base_url to support refactoring changes, however this has broken the logout link.
https://github.com/alphagov/di-infrastructure/pull/428
#189

BAU: Handle trailing '/' on op_base_url for logout

---

src/main/java/uk/gov/di/utils/Oidc.java

Send clientId value in the doc app request object.
Following on from OIDC refactorings in the stub, the doc app journey in build is failing with 'unauthorized_client' as the client id value is not being passed in the request object.
#192 
#189 
https://github.com/alphagov/di-infrastructure/pull/428

BAU: Send clientId value in the doc app request object

---

.gitignore
deploy-sandpit.sh
src/main/java/uk/gov/di/utils/Oidc.java

'buildLogoutUri' refactoring.
Remove 'System.out'.
Git ignore and deploy sandpit tweaks.
A more elegant way to build the logout uri.
#192

BAU: buildLogoutUri refactoring 

---

src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
src/main/resources/templates/userinfo.mustache
startup.sh

Show 'locale' claim on user-info screen.
See section '5.1.  Standard Claims':
https://openid.net/specs/openid-connect-core-1_0.html
'locale' is a standard claim indicating the end-user's locale.
Added to the stub to enable testing when providing this claim is added to the oidc api.

AUT-805: Show 'locale' claim on user-info screen

---

deploy-sandpit.sh

Update oidc base url after sandpit dns changes.
Sandpit domain names have been updated to follow the pattern used by the other environments.

BAU: Update oidc base url after sandpit dns changes

---

manifest.yml

Reduce stub app memory limit.
Stubs are currently only consuming around 100M so lowering the limit to save memory (with a view to adding additional stubs).

AUT-1138: Reduce stub app memory limit

---

build.gradle

Updated jetty-server dependency to 12.0.2. Also added current jetty-xml, json-smart and jackson-databind dependencies
Jetty server dependency needed to be updated to address vulnerability identified in IT health check. Other dependencies were added to address vulnerabilities identified by Checkmarx

AUT-1836: fixed unsafe dependencies

---

src/main/java/uk/gov/di/handlers/ErrorHandler.java

Set "Server" response heading value to "govuk-sign-in-stub-rp" when response status is 500
This is to prevent responses from containing information that allows for identification of technologies used and potential exploits. The ITHC identified an issue with the jetty version being shown in responses as vulnerable.
The ITHC recommended solution of implementing a start.ini file containing `jetty.httpConfig.sendServerVersion=false` would not work with the current build as jetty-server embedded with spark does accept configuration in that way. 
The problem was only identified in responses with status 500. As 500 response codes are only handled by the ErrorHandler.java file, a different "Server" header value of "govuk-sign-in-stub-rp" was assigned in the handle method to match that of other …

AUT-1837: fixed verbose response header

---

.gitignore
src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
src/main/java/uk/gov/di/utils/Oidc.java
src/main/resources/templates/home.mustache
src/main/resources/templates/post-page.mustache

This PR adds capability to the stub to optionally run flows using request objects (JAR) rather than query parameters in the authorisation request to GOV.UK One Login
We can test and demonstrate the matrix of flows that our API supports

ATO-21: Request object flow in stubs (auth-only)

---

src/main/java/uk/gov/di/utils/Oidc.java

This serialises the `vtr` field on request objects as a list rather than as a stringified list, in accordance with the JWT spec
Before:
```
{
...
"vtr": "[\"Cl.Cm\"]"
...
}
```
After:
```
{
...
"vtr": [
"Cl.Cm"
]
...
}
```

ATO-202: Properly serialise `vtr` as a field rather than a serialised string

---

src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
src/main/resources/templates/home.mustache
src/main/resources/templates/userinfo.mustache

Add Return Code claim to stub.
To test whether the Return Code claim is returned successfully.
https://github.com/govuk-one-login/authentication-api/pull/3724

ATO-242: Update stub to support Return Code claim

---

src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
src/main/resources/templates/home.mustache

Added textbox that accepts raw identity inheritance jwt.
Structure of this JWT can be found in draft [ADR](https://github.com/govuk-one-login/architecture/pull/554)
Testing identity inheritance
[ATO-19](https://govukverify.atlassian.net/jira/software/c/projects/ATO/boards/390?selectedIssue=ATO-19)
[ATO-19]: https://govukverify.atlassian.net/browse/ATO-19?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ATO-131: Add indentity Inheritance textbox and handler
